/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for [`Plugmem::new`]. */
export interface OpenOptions {
  /**
   * Embedding dimension (`Config::dim`). Omit or 0 to keep vectors off. When
   * the config file configures an `[embedder]`, that embedder's dimension is
   * authoritative and this — if given — must agree with it.
   */
  dim?: number
  /**
   * Open read-only over another process's writer (requires a checkpointed
   * database). The write verbs then throw; `generation`/`refresh` appear.
   *
   * A text `recall` still reaches the vector source: the engine cannot embed
   * on a read-only handle (replaying into it would defeat the zero-copy
   * open), so this binding embeds the query itself before asking — the same
   * thing the CLI and the MCP server do for their read-only paths.
   */
  readOnly?: boolean
  /**
   * Path to a `config.toml` (`[database]` / `[engine]` / `[embedder]` /
   * `[maintenance]`). When the constructor path is omitted, `[database].path`
   * participates in database-path resolution.
   * Omitted, the standard discovery applies — `$PLUGMEM_CONFIG`, then
   * `$XDG_CONFIG_HOME/plugmem/config.toml` — exactly as the CLI and MCP
   * server resolve it. The `[embedder]` section is what makes a text-only
   * `remember`/`recall` auto-embed; with no config there is no embedder
   * (lexical, tag, graph and time recall still answer).
   */
  config?: string
}
/** One typed edge on a remembered fact: `entity` gains relation `rel`. */
export interface LinkRef {
  /** The relation name. */
  rel: string
  /** The target entity name. */
  entity: string
}
/** Arguments for [`Plugmem::remember`] / [`Plugmem::revise`]. */
export interface RememberArgs {
  /** The fact text (required). */
  text: string
  /** Subject entity name. */
  entity?: string
  /** Tag strings. */
  tags?: Array<string>
  /** Typed edges to attach. */
  links?: Array<LinkRef>
  /**
   * Opaque metadata as a key→value map (a URI to the real payload, a mime
   * type, an external key). The engine never interprets it.
   */
  metadata?: Record<string, string>
  /** Validity start, unix milliseconds (default: the fact's record time). */
  validFrom?: number
  /**
   * A precomputed embedding. Its length must equal the configured `dim`.
   *
   * Given, it **replaces** the embedder: nothing is sent to the provider.
   * That is the host's own precedence — it embeds only when this is absent —
   * and it is the route for a vector you already have, or for a model that
   * is not an OpenAI-shaped HTTP endpoint.
   */
  vector?: Array<number>
}
/**
 * Arguments for [`Plugmem::recall`] — every field optional; lexical/tag/graph/
 * time still answer with no query vector.
 */
export interface RecallArgs {
  /** Free-text query (embedded by the engine when an embedder is configured). */
  query?: string
  /** Restrict to facts carrying all these tags. */
  tags?: Array<string>
  /** Anchor entities for the graph source. */
  entities?: Array<string>
  /** "What was true at" this instant, unix milliseconds (bitemporal as-of). */
  asOf?: number
  /** Time window `[from, to)` over `recorded_at`, unix milliseconds. */
  range?: Array<number>
  /** Max facts to return (0 = engine default). */
  k?: number
  /** Include closed revisions (default false). */
  closed?: boolean
  /**
   * Token budget of the `rendered` block (default 512). That block is what
   * goes into a prompt, so this is the knob deciding how much of the
   * context window a recall may spend.
   */
  tokenBudget?: number
  /**
   * HNSW beam width for the vector source (default: the configured
   * `hnsw_ef_search`). Higher is more accurate and slower; ignored while
   * the engine is still in the flat regime, below `flat_to_hnsw`.
   */
  ef?: number
  /**
   * How many edges the graph source may follow from an anchor entity
   * (default: the configured `graph_depth`). `0` asks for the anchors' own
   * facts and no neighbours.
   *
   * Per call for the same reason `k` and `tokenBudget` are: how wide a net
   * to cast belongs to the question. "What is known around this person"
   * wants more hops than "what is this person's stated preference".
   */
  graphDepth?: number
  /**
   * A precomputed embedding. Its length must equal the configured `dim`.
   *
   * Given, it **replaces** the embedder: nothing is sent to the provider.
   * That is the host's own precedence — it embeds only when this is absent —
   * and it is the route for a vector you already have, or for a model that
   * is not an OpenAI-shaped HTTP endpoint.
   */
  vector?: Array<number>
}
/** Arguments for [`Plugmem::link`]. */
export interface LinkArgs {
  /** Source entity name. */
  src: string
  /** Relation name. */
  rel: string
  /** Destination entity name. */
  dst: string
  /**
   * The fact this edge follows from, recorded on the edge and returned by
   * graph recall — the answer to "why is this edge here". Ignored by
   * `unlink`, which closes an edge rather than opening one.
   */
  provenance?: number
}
/** Bounded tag-catalog options. Omitted fields select the first 64 entries. */
export interface TagListOptions {
  /** Exact, case-sensitive prefix. */
  prefix?: string
  /** Opaque cursor returned by the previous page. */
  cursor?: string
  /** Page size (maximum 256). */
  limit?: number
}
/** Options for [`recover`]. */
export interface RecoverOptions {
  /**
   * Embedding dimension, as `OpenOptions.dim`. It must match what the source
   * database stores, so a memory with vectors needs this (or a `config`
   * naming the embedder) or the salvage cannot open it.
   */
  dim?: number
  /** Path to a `config.toml`; the standard discovery applies when omitted. */
  config?: string
}
/**
 * Salvages a content-corrupt memory: reads `src`, drops the facts that fail
 * the content checks, and writes a clean, compacted image to `dst`.
 *
 * **`src` is never written.** The damaged file stays exactly as it was, as
 * evidence — this produces a repaired copy beside it, and swapping them is
 * your decision, not this function's. `dst` must therefore be a different
 * path.
 *
 * **It handles *content* damage**, the kind `verify` reports: text that is not
 * valid UTF-8, a vector slot that disagrees with its fact, metadata that will
 * not decode. *Structural* damage — a snapshot whose container will not parse
 * at all — is not salvageable here and rejects; that is what a backup is for.
 *
 * Memory stays proportional to the record count rather than the image: the
 * two large pools are streamed through temp files, so a database far bigger
 * than RAM can be recovered as long as its graph fits.
 *
 * **Async**: it opens, sweeps and rewrites a whole database.
 *
 * @throws `PLUGMEM_LOCKED` if either path is open elsewhere; `PLUGMEM_ENGINE`
 * if `dst` resolves to the same file as `src`, or the source will not parse;
 * `PLUGMEM_OPEN` for an IO failure on either path.
 */
export declare function recover(src: string, dst: string, options?: RecoverOptions | undefined | null): Promise<RecoverReport>
/** Options for `Plugmem#scrub`. */
export interface ScrubOptions {
  /**
   * Bytes to hash per step, at most. Default: the engine's own (1 MiB).
   *
   * This is the knob trading responsiveness for throughput: smaller steps
   * return to JavaScript more often, larger ones spend less time crossing
   * back and forth. It changes no answer, only the grain.
   */
  budget?: number
}
/** One similar / potentially-conflicting live fact surfaced by `remember`. */
export interface Similar {
  /** The existing fact's id. */
  id: number
  /** Match strength (higher = closer). */
  score: number
  /** What triggered the hint: `"LexicalOverlap"` or `"VectorCosine"`. */
  reason: string
}
/** The result of `remember` / `revise`. */
export interface RememberOutcome {
  /** The new fact's id. */
  id: number
  /** The subject entity id, if one was named. */
  entity?: number
  /**
   * Similar / potentially-conflicting live facts (best first; the engine
   * never merges on its own — the caller decides).
   */
  similar: Array<Similar>
}
/**
 * Result of `rememberGuarded`. Blocked results have no `outcome` because no
 * fact id was allocated.
 */
export interface GuardedRememberOutcome {
  status: 'stored' | 'blocked'
  outcome?: RememberOutcome
  similar: Array<Similar>
  /**
   * Whether the similarity detector had anything to compare against.
   *
   * `false` means the fact was stored WITHOUT a duplicate check: the
   * detector is scoped to the fact's entity, so a call carrying no
   * `entity` has no candidate set and cannot block anything, now or after
   * any number of later writes. Always `true` on a blocked result, which
   * by definition compared something.
   */
  checked: boolean
}
/** One recalled fact. */
export interface RecalledFact {
  /** The fact id. */
  id: number
  /** Fused score (reciprocal-rank fusion + recency). */
  score: number
  /** Bit set of the sources that surfaced it. */
  sources: number
  /** Subject entity id (a sentinel when none). */
  entity: number
  /** Knowledge axis: when the memory learned it (unix ms). */
  recordedAt: number
  /** Truth axis start (unix ms). */
  validFrom: number
  /** Truth axis end (unix ms), or the open sentinel — see the module note. */
  validTo: number
}
/** One edge walked by the graph source. */
export interface RecalledEdge {
  /** Source entity id. */
  src: number
  /** Relation term id. */
  rel: number
  /** Destination entity id. */
  dst: number
  /** Provenance fact id (a sentinel when none). */
  provenance: number
}
/** A recall response: the structured hits plus the prompt-ready block. */
export interface RecallResult {
  /** Selected facts, descending fused score. */
  facts: Array<RecalledFact>
  /** Edges the graph source walked (deduplicated). */
  edges: Array<RecalledEdge>
  /** The compact prompt block (empty when nothing was found). */
  rendered: string
  /** `true` when selection stopped at `k`/the token budget with more left. */
  truncated: boolean
}
/** Engine size counters. */
export interface Stats {
  /** Fact records stored (live, closed and tombstoned-awaiting-maintain). */
  facts: number
  /** Entities. */
  entities: number
  /** Interned terms (tokens, tags, relations, names). */
  terms: number
  /** Directed edges. */
  edges: number
  /** Historical edge versions, including closed versions. */
  edgeVersions: number
  /** Quantized vector slots. */
  vectors: number
  /** Tombstoned fact records awaiting physical purge. */
  tombstones: number
  /** Vector slots covered by HNSW. */
  hnswIndexed: number
  /** The next fact id to be assigned. */
  nextFact: number
  /** The next entity id to be assigned. */
  nextEntity: number
  /** The next edge-version id to be assigned. */
  nextEdge: number
  /** Total bytes held by the engine's pools. */
  poolBytes: number
}
/**
 * The raw record behind a [`FactSnapshot`] — temporality and flags. (Internal
 * pointers — the blob/vector slots and the reserved `kind` — are omitted.)
 */
export interface FactRecord {
  /** The fact id. */
  id: number
  /** Subject entity id (a sentinel when none). */
  entity: number
  /** Bit set of fact flags (tombstone / closed / has-vector). */
  flags: number
  /** Predecessor in the revision chain (a sentinel when none). */
  revises: number
  /** Knowledge axis: when the memory learned it (unix ms). */
  recordedAt: number
  /** Truth axis start (unix ms). */
  validFrom: number
  /** Truth axis end (unix ms), or the open sentinel — see the module note. */
  validTo: number
}
/** One fact's full card (from `get`). */
export interface FactSnapshot {
  /** The raw record (temporality, flags, references). */
  record: FactRecord
  /** The fact text. */
  text: string
  /**
   * The fact's metadata as a key→value map (empty when it has none). Opaque
   * to the engine — a URI to the real payload, a mime type, an external key.
   */
  metadata: Record<string, string>
}
/** One exported fact — the id-free, import-ready shape. */
export interface ExportedFact {
  /**
   * The fact's id in the database it came from. Informational: an import
   * assigns fresh ids. Present because edges name their provenance fact by
   * id, so a dump carrying edges needs something for them to point at.
   */
  id: number
  /** The fact text. */
  text: string
  /** Subject entity name, if any. */
  entity?: string
  /** Tag strings. */
  tags: Array<string>
  /** Metadata as a key→value map (empty when none); preserved on import. */
  metadata: Record<string, string>
  /** When the memory learned it (unix ms; informational). */
  recordedAt: number
  /** Validity start (unix ms; preserved on import). */
  validFrom: number
}
/**
 * One exported edge — the shape `exportEdges` streams, and the same fields the
 * CLI's JSONL dump writes for an edge.
 *
 * Edges are not part of a fact's dump: a fact names its tags and metadata, but
 * an edge is a statement *between* two entities and outlives any single fact.
 * That is why a complete backup is the two streams together.
 */
export interface ExportedEdge {
  /** Source entity name. */
  src: string
  /** The relation, verbatim. */
  rel: string
  /** Destination entity name. */
  dst: string
  /**
   * The fact this edge follows from, if it was recorded with one. Absent
   * rather than a sentinel, so "no provenance" cannot be mistaken for fact 0.
   */
  provenance?: number
}
/**
 * What a `recover` salvaged, and what it had to leave behind.
 *
 * The three `dropped` counts are the damage: each is a fact the source could
 * not produce intact, so a non-zero total means the recovered copy is smaller
 * than the original claimed to be. Zeroes across the board mean the image was
 * content-clean and this was a compaction.
 */
export interface RecoverReport {
  /** Facts written to the destination — the survivors. */
  kept: number
  /** Dropped: the stored text was not valid UTF-8. */
  droppedText: number
  /** Dropped: the vector slot was out of range or disagreed with the fact. */
  droppedVector: number
  /** Dropped: the metadata blob did not decode to a well-formed map. */
  droppedMetadata: number
}
/** How far a `Scrub` has got. */
export interface ScrubProgress {
  /** Bytes checksummed so far; equals `totalBytes` on the last step. */
  doneBytes: number
  /** The generation file's length — the total to checksum. */
  totalBytes: number
}
/** One bounded page returned by `exportPage`. */
export interface ExportPage {
  /** Open facts in fact-id order; never longer than the native page bound. */
  facts: Array<ExportedFact>
  /** Pass this opaque cursor to the next call; absent when the scan is done. */
  nextCursor?: number
}
/** One active tag and the number of current facts carrying it. */
export interface TagSummary {
  name: string
  count: number
}
/** One bounded, stable page of current tags. */
export interface TagPage {
  items: Array<TagSummary>
  nextCursor?: string
}
/** Result of removing one tag from all current facts. */
export interface RemoveTagReport {
  affected: number
}
/** The report of an explicit complete vector-axis replacement. */
export interface ReembedReport {
  previousSpace?: string
  newSpace: string
  previousDim: number
  newDim: number
  embedded: number
  tombstonesSkipped: number
  vectorBytes: number
  hnswIndexed: number
}
/** The report of a `maintain` pass. */
export interface MaintainReport {
  /** Tombstoned facts physically removed by this pass. */
  purged: number
  /** On-disk image bytes before the pass. */
  bytesBefore: number
  /** On-disk image bytes after the pass. */
  bytesAfter: number
  /** No storage/index rewrite was needed. */
  noOp: boolean
  /** Tombstones present before the pass. */
  tombstonesBefore: number
  /** Fact records before the pass. */
  factsBefore: number
  /** Fact records after the pass. */
  factsAfter: number
  /** Vector slots before the pass. */
  vectorsBefore: number
  /** Vector slots after the pass. */
  vectorsAfter: number
  /** HNSW coverage before the pass. */
  hnswIndexedBefore: number
  /** HNSW coverage after the pass. */
  hnswIndexedAfter: number
  /** Physical compaction ran. */
  structuralCompacted: boolean
  /** BM25 was compacted from existing postings. */
  bm25Compacted: boolean
  /** BM25 was rebuilt from text. */
  bm25Reindexed: boolean
  /** HNSW was rebuilt from empty. */
  hnswRebuilt: boolean
  /** HNSW was carried/remapped. */
  hnswRemapped: boolean
  /** Vector slots inserted into HNSW. */
  hnswInserted: number
  /**
   * The edge arenas were rewritten page-dense (`full` only). No edge
   * version is ever dropped, so the version count is unchanged — only the
   * bytes shrink.
   */
  edgesCompacted: boolean
  /** Current edges before the pass. */
  edgesBefore: number
  /** Historical edge versions before the pass. */
  edgeVersionsBefore: number
}
/** How much work a `maintain` pass should do. */
export const enum MaintainMode {
  /**
   * Only pending work: purge tombstones, refresh a stale text index, and
   * advance the vector graph within a bounded budget. Cheap to run often.
   */
  Auto = 'auto',
  /** Physically purge tombstoned facts and compact storage and indexes. */
  Compact = 'compact',
  /** Rebuild the text index by re-reading and re-tokenizing every fact. */
  ReindexText = 'reindex-text',
  /** Build or advance the vector graph without compacting anything else. */
  OptimizeVectors = 'optimize-vectors',
  /**
   * Rebuild every rebuildable structure, fully optimize vectors and repack
   * the edge arenas. O(database) work; no history is ever dropped.
   */
  Full = 'full'
}
/**
 * One memory as the workspace registry knows it.
 *
 * Hand-mapped rather than serde-round-tripped like the rest of this file:
 * `DbEntry` carries a `DbName`, which is a validated newtype with no serde
 * derive, and giving one to a public host type only so a wrapper could
 * round-trip it would be the wrong direction of dependency.
 */
export interface DbEntry {
  /** The memory's name — its identity, and what `Workspace.memory` takes. */
  db: string
  /** What it is for. */
  description: string
  /** Its tags. */
  tags: Array<string>
  /** Its owner, if recorded. */
  owner?: string
  /** Whether it is labelled archived. */
  archived: boolean
}
/** What a `Workspace.reindex()` pass did. */
export interface ReindexReport {
  /** Memories whose own description was copied into the registry. */
  indexed: Array<string>
  /**
   * Memories nobody has described. Not a fault — a memory works without a
   * description; it just cannot be found by one.
   */
  undescribed: Array<string>
  /**
   * Memories another process holds open, so this pass could not read them.
   * Named rather than skipped silently: the registry is knowingly incomplete.
   */
  busy: Array<string>
}
/** Something `Workspace.verify()` found. Reported, never repaired. */
export interface WorkspaceProblem {
  /** The memory it concerns (empty for a kind this binding does not know). */
  db: string
  /**
   * What kind: `"missing"`, `"undescribed"`, `"stale"`, `"unreadable"`,
   * `"ambiguous-self"`. The same vocabulary the CLI prints in `--json`.
   */
  issue: string
  /** More detail, where the kind carries any. */
  detail?: string
}
/** Options for [`Workspace::new`]. */
export interface WorkspaceOptions {
  /**
   * Embedding dimension, as in [`crate::db::OpenOptions`]. Applies to every
   * memory in the workspace and to the registry.
   */
  dim?: number
  /**
   * Path to a `config.toml`. Resolution is the standard one when omitted.
   * Its `[workspace]` section supplies the pool defaults below.
   */
  config?: string
  /**
   * Memories kept open at once; the least recently used is closed to make
   * room. Defaults to `[workspace].max_open`, else 16.
   */
  maxOpen?: number
  /**
   * Milliseconds a memory may sit unused before `closeIdle()` closes it.
   * `0` disables the sweep. Defaults to `[workspace].idle_timeout_ms`, else
   * 60000.
   *
   * This is a liveness setting, not a memory one: an open memory holds the
   * file's exclusive lock, so a long-running process that never let go would
   * make its memories unreachable from anything else on the machine.
   */
  idleTimeoutMs?: number
}
/** What to record about a memory — the argument of [`Workspace::describe`]. */
export interface DescribeArgs {
  /**
   * What this memory is for, in the words someone would search with. This is
   * the text `find` matches.
   */
  description: string
  /** Tags to filter by. */
  tags?: Array<string>
  /**
   * Who it belongs to. Recorded as a graph edge, so `find("ann")` returns
   * what Ann owns even though no description mentions her.
   */
  owner?: string
}
/**
 * The engine/package version (the workspace version; the npm package tracks
 * it release-for-release).
 */
export declare function version(): string
/** A short, version-free description pointing the caller at the skill. */
export declare function about(): string
/** One config.toml setting returned by [`settings_help`]. */
export interface SettingHelpItem {
  /** TOML section name. */
  section: string
  /** TOML key name. */
  key: string
  /** Human-readable value type. */
  valueType: string
  /** Displayed default value. */
  defaultValue: string
  /** Setting behavior. */
  description: string
  /** Owning surface: shared, CLI or MCP. */
  scope: string
}
/** Complete config.toml help returned by [`settings_help`]. */
export interface SettingsHelpResult {
  /** Config discovery order from highest to lowest precedence. */
  configPathPrecedence: Array<string>
  /** Resolved platform default config path, if the OS exposes a user home. */
  defaultConfigPath?: string
  /** Every supported config.toml setting. */
  settings: Array<SettingHelpItem>
}
/** Return the complete settings catalogue without opening a database. */
export declare function settingsHelp(): SettingsHelpResult
/**
 * The companion skill for napi consumers: the canonical `SKILL.md` with the
 * CLI/MCP "Run it" appendix removed (a napi host has one transport and always
 * ships skill and engine from the same release, so that ceremony never applies).
 */
export declare function skill(): string
/** The canonical, unstripped `SKILL.md` (what CLI/MCP consumers read). */
export declare function skillFull(): string
/**
 * The `<!-- skill-version: X.Y.Z -->` marker value from the canonical skill
 * (read from the raw text, so the marker living inside the stripped block is
 * still visible here).
 */
export declare function skillVersion(): string
/**
 * A memory over one plugmem file — the napi mirror of [`plugmem_host::Database`]
 * (writer) or [`plugmem_host::ReadOnlyDatabase`] (with `{ readOnly: true }`).
 * Construct it, call the verbs, and `close()` it to release the file when done.
 */
export declare class Plugmem {
  /**
   * Opens (or creates) the memory at `path` and resolves with the handle. If
   * `path` is omitted, resolution is `PLUGMEM_DB` > `[database].path` > the
   * platform data path — and [`path()`](Plugmem::path) reports what that was.
   *
   * **A static method, not a constructor, and that is the point.** Opening
   * takes the file's exclusive lock, replays the journal and maps the
   * snapshot — work proportional to what is on disk. A JavaScript
   * constructor must evaluate to its object immediately, so `new` has no way
   * to hand that to a worker: it would run on the one thread that executes
   * JavaScript and freeze the process for the length of the replay. A static
   * method can return a `Promise`, so it does.
   *
   * @throws synchronously on a config error (the file is read before any
   * work is scheduled); rejects if another writer holds the lock
   * (`PLUGMEM_LOCKED`), if `readOnly` is set on a database with no published
   * snapshot (`PLUGMEM_NEEDS_CHECKPOINT`), or on an IO error.
   */
  static open(path?: string | undefined | null, options?: OpenOptions | undefined | null): Promise<Plugmem>
  /**
   * What `config.toml` said that nothing claimed — a misspelled key, a
   * misspelled section — one human-readable line each, empty when the file
   * was clean.
   *
   * It is a value rather than a printed warning because a native addon has
   * nowhere sensible to print: stderr belongs to the host application, which
   * may be a server that logs as JSON. **Read it once after opening and log
   * it your own way** — ignoring it puts you back where a typo silently
   * changes nothing.
   */
  configWarnings(): Array<string>
  /**
   * The file this memory is open on.
   *
   * Worth having because the constructor may resolve the path rather than be
   * given one — `PLUGMEM_DB`, then `[database].path`, then the platform data
   * path — and `new Plugmem()` with no argument otherwise leaves the caller
   * unable to say which file it just wrote to.
   */
  path(): string
  /**
   * Stores a fact and resolves with its id plus similar/conflicting live
   * facts.
   *
   * **Async** (returns a `Promise`): with an `[embedder]` configured this
   * makes an HTTP call to the provider, and a write waits for the journal's
   * durability policy. Both are blocking work, and Node has exactly one
   * thread that runs JavaScript — doing them on it would freeze every timer,
   * socket and callback in the process for the whole round trip. It runs on
   * a libuv worker instead. Arguments are still checked synchronously, so a
   * refused one throws here rather than rejecting later.
   * @throws synchronously in read-only mode.
   */
  remember(args: RememberArgs): Promise<RememberOutcome>
  /**
   * Stores only when the same bounded Jaccard/cosine detector used by
   * `remember().similar` finds no candidate. No other write can slip between
   * the check and possible write; a blocked result performs no mutation.
   * Runs on a libuv worker because
   * automatic embedding and durable writes are blocking work.
   */
  rememberGuarded(args: RememberArgs): Promise<GuardedRememberOutcome>
  /**
   * Stores a batch of facts and resolves with one outcome per input.
   *
   * A batch may call a remote embedder and always performs one journal sync,
   * so it runs on napi-rs' libuv worker pool.
   */
  rememberMany(args: Array<RememberArgs>): Promise<RememberOutcome[]>
  /**
   * Closes fact `id`, records `args` as its successor, and resolves with the
   * outcome. **Async** for the same reasons as
   * [`remember`](Plugmem::remember).
   * @throws synchronously in read-only mode.
   */
  revise(id: number, args: RememberArgs): Promise<RememberOutcome>
  /**
   * Ranked, fused recall. Resolves with the structured result (its `rendered`
   * field is the prompt-ready block; `facts`/`edges` are the structured hits).
   *
   * **Async** (returns a `Promise`): a text query with an `[embedder]`
   * configured costs an HTTP round trip, and blocking the one thread that
   * runs JavaScript for it would stall the whole process. The query shape is
   * still validated synchronously.
   */
  recall(args?: RecallArgs | undefined | null): Promise<RecallResult>
  /**
   * Tombstones fact `id` (physically purged at the next `maintain`) and
   * resolves with whether it was a live fact.
   *
   * **Async**: every write syncs the journal, and the host's post-write
   * policy can fire a whole maintenance pass or a reshard from here — work
   * proportional to the database, which the JS thread must not be holding.
   * @throws synchronously in read-only mode.
   */
  forget(id: number): Promise<boolean>
  /**
   * Tombstones many facts at once. Equivalent to [`forget`](Plugmem::forget)
   * on each id in order, but under **one** journal sync and **one**
   * post-write policy pass instead of N — the same batching
   * [`rememberMany`](Plugmem::remember_many) does for writes. Resolves with
   * one boolean per id, in the same order, `true` when that id was live.
   * @throws synchronously in read-only mode.
   */
  forgetMany(ids: Array<number>): Promise<boolean[]>
  /**
   * Upserts a typed edge `src -rel-> dst`. **Async** for the same reason as
   * [`forget`](Plugmem::forget). @throws synchronously in read-only mode.
   */
  link(args: LinkArgs): Promise<void>
  /**
   * Closes the current typed edge `src -rel-> dst`, resolving with whether
   * one was open. **Async** for the same reason as
   * [`forget`](Plugmem::forget). @throws synchronously in read-only mode.
   */
  unlink(args: LinkArgs): Promise<boolean>
  /** One fact's full card by `id`, or `null` if unknown/tombstoned. */
  get(id: number): FactSnapshot | null
  /** Engine size counters. */
  stats(): Stats
  /**
   * Every currently-open fact, as one array (id-free, import-ready).
   *
   * **Async, but still unbounded, in two ways.** The scan runs on a worker,
   * yet the whole memory is materialized into a single array before it
   * resolves, so peak memory is the whole export. And `resolve` runs on the
   * JS thread by definition, so building one JavaScript object per fact
   * stalls it: measured at ~244 ms of a 289 ms call over 100 000 facts,
   * against 0 ms for the same data through `exportPage`. A promise hides
   * neither cost. Prefer `exportPage` for anything but a small memory or a
   * script.
   */
  export(): Promise<ExportedFact[]>
  /**
   * Returns at most 128 inspected fact ids' open facts on a libuv worker
   * thread. A sparse page can be empty and still carry `nextCursor`.
   *
   * Pass `nextCursor` back as `cursor` until it is absent. Each Promise owns
   * exactly one bounded page and resolves only after its native scan has
   * completed; there is no callback queue and no database lock held while JS
   * processes the result. A writer may change between page calls, so do not
   * mutate it during a snapshot-style backup; a read-only handle is stable.
   */
  exportPage(cursor?: number | undefined | null): Promise<ExportPage>
  /**
   * Streams every current edge to `onBatch`, in batches, and resolves with
   * the number streamed.
   *
   * **The other half of a backup.** `export`/`exportPage` dump facts; an edge
   * is a statement between two entities and belongs to no single fact, so a
   * dump of facts alone silently loses the graph.
   *
   * **Async and bounded.** The walk runs on a libuv worker; batches reach
   * `onBatch` on the JS thread through a threadsafe function with a queue of
   * four. When the callback is slower than the walk, the *worker* waits — the
   * event loop never does, and peak memory is four batches whatever the
   * database's size.
   *
   * **When the promise resolves, every batch has been delivered.** Worth
   * saying because a threadsafe-function call only queues work for the JS
   * thread, so the natural implementation resolves early and hands you a
   * half-filled accumulator on some runs and a full one on others. Each
   * batch is acknowledged from the JS thread and the worker waits for the
   * receipts, so reading your results straight after the `await` is correct.
   *
   * `onBatch` throwing is not caught here: it surfaces as an uncaught error,
   * as it would from any callback Node invokes on your behalf.
   */
  exportEdges(onBatch: (edges: ExportedEdge[]) => void): Promise<number>
  /**
   * Starts a resumable byte-level check of the current published snapshot,
   * and resolves with the [`Scrub`](crate::scrub::Scrub) that paces it.
   *
   * The counterpart to `verify`, not a replacement: `verify` asks whether
   * the *content* agrees with itself, this asks whether the *bytes* are the
   * ones that were written. Only the second catches a flipped bit that the
   * structure accepts.
   *
   * Available on a writer as well as a read-only handle: a scrub reads the
   * published generation from disk and has no opinion about which handle
   * asked. It does need something published — checkpoint once first.
   *
   * **The returned object holds a shared lock** on the generation it scans
   * for as long as it lives, so run it to completion or `close()` it.
   *
   * @throws `PLUGMEM_NEEDS_CHECKPOINT` when nothing has been published yet.
   */
  scrub(options?: ScrubOptions | undefined | null): Promise<Scrub>
  /** One fact's tags, or an empty array for an unknown or tombstoned id. */
  tagsOf(id: number): Array<string>
  /**
   * One bounded page of current tags. Runs on a libuv worker so neither a
   * mapped-page fault nor host locking can pause the JavaScript event loop.
   */
  listTags(options?: TagListOptions | undefined | null): Promise<TagPage>
  /**
   * Removes a tag from every current fact by creating successor revisions.
   * The bulk write and journal sync run on a libuv worker.
   * @throws synchronously in read-only mode.
   */
  removeTag(tag: string): Promise<RemoveTagReport>
  /**
   * Content-integrity check; rejects on the first inconsistency found.
   *
   * **Async**: this is a full sweep — every fact's text and metadata, the
   * vector mapping, and both directions of every edge. On a large memory
   * that is seconds of work, and it belongs on a worker.
   */
  verify(): Promise<void>
  /**
   * Runs policy-driven maintenance; resolves with the before/after report.
   * **Async** (returns a `Promise`): the pass may do disk I/O (compaction,
   * HNSW work), so it runs on a libuv worker thread and never blocks the
   * event loop. @throws synchronously in read-only mode.
   *
   * `mode` defaults to `auto`, which does only what is pending. `full`
   * rebuilds everything and repacks the edge arenas — O(database) work, and
   * the only mode that reclaims edge-history page slack.
   */
  maintain(mode?: 'auto' | 'compact' | 'reindex-text' | 'optimize-vectors' | 'full'): Promise<MaintainReport>
  /**
   * Explicitly recomputes every retained fact with the configured embedder
   * and atomically replaces the complete vector axis. This is never invoked
   * by `maintain('auto')`.
   *
   * **Async**: provider and snapshot work runs on a libuv worker; the event
   * loop remains responsive. Reads continue while it runs and writes reject
   * with `PLUGMEM_BUSY` instead of waiting.
   */
  reembed(batchSize?: number | undefined | null): Promise<ReembedReport>
  /**
   * Flushes the journal into a fresh snapshot. **Async** (returns a `Promise`):
   * it writes and fsyncs a snapshot file, so it runs on a libuv worker thread.
   * @throws synchronously in read-only mode.
   */
  checkpoint(): Promise<void>
  /**
   * The pinned snapshot generation (read-only mode only).
   * @throws on a writer.
   */
  generation(): number
  /**
   * Advance to the writer's latest published checkpoint (read-only mode only);
   * returns whether a newer generation was adopted. @throws on a writer.
   */
  refresh(): boolean
  /**
   * Releases the file and its lock. Every verb afterwards throws; calling it
   * again is a no-op. (The handle is also released when the object is GC'd,
   * but `close()` makes the moment explicit — e.g. before a read-only reopen.)
   */
  close(): void
  /**
   * Whether this handle has an embedder, and whether it is usable now.
   *
   * `"absent"` when none is configured, `"active"` when it is being called,
   * `"suspended"` when it is not — either because `suspendEmbedder()` said
   * so, or because it failed under `on_error = "degrade"`. A suspended
   * memory still remembers, still recalls and still forgets; what it does
   * not do is meaning-based ranking.
   */
  embedderState(): 'absent' | 'active' | 'suspended'
  /**
   * Stops calling the embedder until `resumeEmbedder()`.
   *
   * For when the caller knows the provider is gone — the machine went
   * offline, the model was unloaded — and would rather not pay one failed
   * request per verb to rediscover it. Writes made meanwhile store no
   * vector; `reembed()` fills them in later. Idempotent, and a no-op
   * without an embedder. Works on a read-only handle too, which is the one
   * that embeds its own queries.
   */
  suspendEmbedder(): void
  /**
   * Calls the embedder again. Nothing is verified here: the next verb that
   * needs a vector finds out, and suspends it again if it is still down.
   */
  resumeEmbedder(): void
}
/**
 * A resumable byte-level check of one snapshot generation.
 *
 * **Holding this object holds a lock.** It pins the generation it is scanning
 * with a shared lock for its whole life, so the writer's garbage collection
 * cannot reclaim that generation under it. Finish the scan, or `close()` it —
 * do not park one indefinitely.
 *
 * One-shot: once it has returned `null`, or thrown, it is done. Ask the
 * database for another to scan again.
 */
export declare class Scrub {
  /**
   * Hashes the next slice and resolves with the progress so far, or `null`
   * when the scan is complete.
   *
   * **Async**: see the module note — a step is disk I/O, not arithmetic.
   *
   * Concurrent calls are serialized rather than refused: the cursor has one
   * position, so two overlapping steps would be two different slices of the
   * same scan, which is what a caller pacing it from two places asked for.
   *
   * @throws on the first mismatch, naming what failed its checksum. The
   * scrub is finished at that point; a further call resolves `null`.
   */
  next(): Promise<ScrubProgress | null>
  /**
   * Releases the pinned generation now, abandoning an unfinished scan.
   *
   * Idempotent, and the same bargain as `Plugmem#close`: waiting for the
   * garbage collector to do it means the writer cannot reclaim that
   * generation until it happens.
   */
  close(): void
  /**
   * Whether this scrub still has work — `false` once it finished, failed or
   * was closed. Cheap: it inspects the handle, not the file.
   */
  active(): boolean
}
/**
 * A logical reference to one named memory.
 *
 * It owns no open database and no file lock. Each verb obtains a scoped
 * workspace lease on a libuv worker, and dropping this JavaScript object has
 * no resource-management meaning. The workspace is the owner; closing it
 * invalidates every reference.
 */
export declare class WorkspaceMemory {
  /** The stable workspace name this reference addresses. */
  name(): string
  remember(args: RememberArgs): Promise<RememberOutcome>
  rememberGuarded(args: RememberArgs): Promise<GuardedRememberOutcome>
  rememberMany(args: Array<RememberArgs>): Promise<RememberOutcome[]>
  revise(id: number, args: RememberArgs): Promise<RememberOutcome>
  recall(args?: RecallArgs | undefined | null): Promise<RecallResult>
  forget(id: number): Promise<boolean>
  forgetMany(ids: Array<number>): Promise<boolean[]>
  link(args: LinkArgs): Promise<void>
  unlink(args: LinkArgs): Promise<boolean>
  get(id: number): Promise<FactSnapshot | null>
  stats(): Promise<Stats>
  export(): Promise<ExportedFact[]>
  exportPage(cursor?: number | undefined | null): Promise<ExportPage>
  exportEdges(onBatch: (edges: ExportedEdge[]) => void): Promise<number>
  scrub(options?: ScrubOptions | undefined | null): Promise<Scrub>
  tagsOf(id: number): Promise<string[]>
  listTags(options?: TagListOptions | undefined | null): Promise<TagPage>
  removeTag(tag: string): Promise<RemoveTagReport>
  verify(): Promise<void>
  maintain(mode?: 'auto' | 'compact' | 'reindex-text' | 'optimize-vectors' | 'full'): Promise<MaintainReport>
  reembed(batchSize?: number | undefined | null): Promise<ReembedReport>
  checkpoint(): Promise<void>
  /**
   * Whether this memory has an embedder, and whether it is usable now:
   * `"absent"`, `"active"` or `"suspended"`.
   *
   * A workspace shares one provider between its memories, but each memory
   * keeps its own gate — so this answers for this memory alone. A sibling
   * that has not called the dead endpoint yet still reports `"active"`.
   */
  embedderState(): Promise<'absent' | 'active' | 'suspended'>
  /**
   * Stops calling this memory's embedder until `resumeEmbedder()`. Writes
   * made meanwhile store no vector; `reembed()` fills them in later.
   */
  suspendEmbedder(): Promise<void>
  /**
   * Calls this memory's embedder again. Nothing is verified here: the next
   * verb that needs a vector finds out, and suspends it again if it is
   * still down.
   */
  resumeEmbedder(): Promise<void>
}
export declare class Workspace {
  /**
   * Opens the workspace rooted at `root`. Creates nothing: the directories
   * appear when a memory is first written.
   *
   * @throws on a config error.
   */
  constructor(root: string, options?: WorkspaceOptions | undefined | null)
  /**
   * Returns a logical reference to the memory named `db`.
   *
   * This does not open a file, acquire a lock or create the memory. Read
   * verbs require it to exist; write verbs create it on first use. The
   * returned object stays valid across pool eviction and `release()` and
   * transparently reopens the memory on its next verb.
   */
  memory(db: string): WorkspaceMemory
  /**
   * Evicts one inactive memory from the pool and releases its file lock.
   *
   * Logical references remain valid. A later verb reopens the memory. If a
   * verb is currently using it, this throws a typed `BUSY` error instead of
   * waiting.
   */
  release(db: string): boolean
  /**
   * Every memory in the directory, sorted by name.
   *
   * Reads the filesystem, not the registry: a memory that exists but was
   * never described still appears.
   * **Async**: it reads the directory.
   */
  list(): Promise<string[]>
  /**
   * Every described memory, sorted by name.
   *
   * **Async**: the registry is itself a memory, so this opens and reads a
   * database.
   */
  entries(): Promise<DbEntry[]>
  /**
   * The memories whose descriptions best match `query`, best first.
   *
   * This is the answer to "I do not know the name": ask in words, get names
   * back, then open by name. A person's name works too — an owner is a graph
   * edge, and the graph source reaches it.
   * **Async**: this is a full recall against the registry memory — the same
   * hybrid retrieval any other recall runs.
   */
  find(query: string, k?: number | undefined | null): Promise<DbEntry[]>
  /**
   * Records what a memory is for — in the memory itself and in the registry,
   * so the registry can always be rebuilt from the memories. Creates the
   * memory if it does not exist.
   *
   * Called again for the same memory this revises rather than duplicating,
   * so the history of what it used to be for is kept.
   * **Async**: it writes twice — into the memory itself and into the
   * registry — and each write syncs a journal.
   */
  describe(db: string, args: DescribeArgs): Promise<void>
  /**
   * Labels a memory archived, keeping its description. Returns whether
   * anything changed. Archiving does not close, move or delete anything.
   *
   * @throws if the memory has no registry record to archive.
   * **Async**: a registry write.
   */
  archive(db: string): Promise<boolean>
  /**
   * Rebuilds the registry from the memories' own descriptions.
   *
   * Runs on a libuv thread: it opens and reads every memory in the
   * directory, which is not work for the main thread. A memory another
   * process holds open cannot be read and is named in the report rather than
   * skipped silently.
   */
  reindex(): Promise<ReindexReport>
  /**
   * Checks the registry against the directory. Reports every disagreement
   * and repairs nothing — a workspace is a directory a person can edit, and
   * guessing at their intent is how a consistency check loses data.
   */
  verify(): Promise<WorkspaceProblem[]>
  /**
   * Closes every memory unused for longer than the idle timeout, returning
   * how many were closed. Call it on a timer: nothing else releases the file
   * lock on a memory nobody is asking about.
   */
  closeIdle(): number
  /** How many memories are open right now. */
  openCount(): number
  /**
   * Invalidates every [`WorkspaceMemory`] reference, closes inactive pooled
   * memories and the registry, and closes the workspace. A verb already in
   * flight finishes with its scoped handle; its lock is released when that
   * verb returns. Every later call throws `CLOSED`.
   */
  close(): void
}
