# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import typing
__all__ = [
    "BusyError",
    "ClosedError",
    "ConfigError",
    "DbEntry",
    "EngineError",
    "ExportPage",
    "ExportedEdge",
    "ExportedFact",
    "FactRecord",
    "FactSnapshot",
    "GuardedRememberOutcome",
    "InternalError",
    "InvalidArgError",
    "InvalidNameError",
    "LockedError",
    "MaintainReport",
    "NeedsCheckpointError",
    "OpenError",
    "Plugmem",
    "PlugmemError",
    "ReadOnlyError",
    "RecallResult",
    "RecalledEdge",
    "RecalledFact",
    "RecoverReport",
    "ReembedReport",
    "ReindexReport",
    "RememberOutcome",
    "RemoveTagReport",
    "Scrub",
    "ScrubProgress",
    "SettingHelpItem",
    "SettingsHelpResult",
    "Similar",
    "StaleCursorError",
    "Stats",
    "TagPage",
    "TagSummary",
    "Workspace",
    "WorkspaceMemory",
    "WorkspaceProblem",
    "WriterOnlyError",
    "about",
    "recover",
    "settings_help",
    "skill",
    "skill_full",
    "skill_version",
    "version",
]

class BusyError(PlugmemError):
    r"""
    Local contention: a handle is in use, or every workspace pool slot is leased by an active operation.
    """
    ...

class ClosedError(PlugmemError):
    r"""
    The handle is closed — `close()` was called on it.
    """
    ...

class ConfigError(PlugmemError):
    r"""
    The `config.toml` could not be read, or a section of it is invalid.
    """
    ...

@typing.final
class DbEntry:
    r"""
    One memory as the workspace registry knows it.
    """
    @property
    def db(self) -> builtins.str:
        r"""
        The memory's name — its identity, and what `Workspace.memory` takes.
        """
    @property
    def description(self) -> builtins.str:
        r"""
        What it is for.
        """
    @property
    def tags(self) -> builtins.list[builtins.str]:
        r"""
        Its tags.
        """
    @property
    def owner(self) -> typing.Optional[builtins.str]:
        r"""
        Its owner, if recorded.
        """
    @property
    def archived(self) -> builtins.bool:
        r"""
        Whether it is labelled archived.
        """
    def __repr__(self) -> builtins.str: ...

class EngineError(PlugmemError):
    r"""
    The engine reported a failure — IO, a capacity limit, a rejected input it alone can judge. The message is the host's own.
    """
    ...

@typing.final
class ExportPage:
    r"""
    One bounded page returned by `export_page`.
    """
    @property
    def facts(self) -> builtins.list[ExportedFact]:
        r"""
        Open facts in fact-id order; never longer than the native page bound.
        """
    @property
    def next_cursor(self) -> typing.Optional[builtins.int]:
        r"""
        Pass this opaque cursor to the next call; `None` when the scan is done.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ExportedEdge:
    r"""
    One exported edge — the shape `export_edges` streams, and the same fields
    the CLI's JSONL dump writes for an edge.
    
    Edges are not part of a fact's dump: a fact names its tags and metadata, but
    an edge is a statement *between* two entities and outlives any single fact.
    That is why a complete backup is the two streams together.
    """
    @property
    def src(self) -> builtins.str:
        r"""
        Source entity name.
        """
    @property
    def rel(self) -> builtins.str:
        r"""
        The relation, verbatim.
        """
    @property
    def dst(self) -> builtins.str:
        r"""
        Destination entity name.
        """
    @property
    def provenance(self) -> typing.Optional[builtins.int]:
        r"""
        The fact this edge follows from, if it was recorded with one. `None`
        rather than a sentinel, so "no provenance" cannot be mistaken for fact 0.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ExportedFact:
    r"""
    One exported fact — the id-free, import-ready shape.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        The fact's id in the database it came from. Informational: an import
        assigns fresh ids. Present because edges name their provenance fact by
        id, so a dump carrying edges needs something for them to point at.
        """
    @property
    def text(self) -> builtins.str:
        r"""
        The fact text.
        """
    @property
    def entity(self) -> typing.Optional[builtins.str]:
        r"""
        Subject entity name, if any.
        """
    @property
    def tags(self) -> builtins.list[builtins.str]:
        r"""
        Tag strings.
        """
    @property
    def metadata(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Metadata as a key→value map (empty when none); preserved on import.
        """
    @property
    def recorded_at(self) -> builtins.int:
        r"""
        When the memory learned it (unix ms; informational).
        """
    @property
    def valid_from(self) -> builtins.int:
        r"""
        Validity start (unix ms; preserved on import).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FactRecord:
    r"""
    The raw record behind a [`FactSnapshot`] — temporality and flags. (Internal
    pointers — the blob/vector slots and the reserved `kind` — are omitted.)
    """
    @property
    def id(self) -> builtins.int:
        r"""
        The fact id.
        """
    @property
    def entity(self) -> builtins.int:
        r"""
        Subject entity id (a sentinel when none).
        """
    @property
    def flags(self) -> builtins.int:
        r"""
        Bit set of fact flags (tombstone / closed / has-vector).
        """
    @property
    def revises(self) -> builtins.int:
        r"""
        Predecessor in the revision chain (a sentinel when none).
        """
    @property
    def recorded_at(self) -> builtins.int:
        r"""
        Knowledge axis: when the memory learned it (unix ms).
        """
    @property
    def valid_from(self) -> builtins.int:
        r"""
        Truth axis start (unix ms).
        """
    @property
    def valid_to(self) -> builtins.int:
        r"""
        Truth axis end (unix ms), or `VALID_TO_OPEN` while the fact is open.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FactSnapshot:
    r"""
    One fact's full card (from `get`).
    """
    @property
    def record(self) -> FactRecord:
        r"""
        The raw record (temporality, flags, references).
        """
    @property
    def text(self) -> builtins.str:
        r"""
        The fact text.
        """
    @property
    def metadata(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        The fact's metadata as a key→value map (empty when it has none). Opaque
        to the engine — a URI to the real payload, a mime type, an external key.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GuardedRememberOutcome:
    r"""
    Result of `remember_guarded`. `status` is `"stored"` or `"blocked"`;
    blocked calls have no `outcome` because they allocate no fact id.
    """
    @property
    def outcome(self) -> typing.Optional[RememberOutcome]: ...
    @property
    def similar(self) -> builtins.list[Similar]: ...
    @property
    def checked(self) -> builtins.bool:
        r"""
        Whether the similarity detector had anything to compare against.
        
        `False` means the fact was stored WITHOUT a duplicate check: the
        detector is scoped to the fact's entity, so a call carrying no
        `entity` has no candidate set and cannot block anything, now or after
        any number of later writes. Always `True` on a blocked result, which
        by definition compared something.
        """
    @property
    def status(self) -> typing.Literal["stored", "blocked"]: ...
    def __repr__(self) -> builtins.str: ...

class InternalError(PlugmemError):
    r"""
    A bug in this binding. Registered for parity with the other bindings' `PLUGMEM_INTERNAL`; this one has no path that raises it.
    """
    ...

class InvalidArgError(PlugmemError):
    r"""
    An argument was refused before it reached the engine.
    """
    ...

class InvalidNameError(PlugmemError):
    r"""
    A memory name is not a usable name.
    """
    ...

class LockedError(PlugmemError):
    r"""
    Another process holds the database's writer lock.
    """
    ...

@typing.final
class MaintainReport:
    r"""
    The report of a `maintain` pass.
    """
    @property
    def purged(self) -> builtins.int:
        r"""
        Tombstoned facts physically removed by this pass.
        """
    @property
    def bytes_before(self) -> builtins.int:
        r"""
        On-disk image bytes before the pass.
        """
    @property
    def bytes_after(self) -> builtins.int:
        r"""
        On-disk image bytes after the pass.
        """
    @property
    def no_op(self) -> builtins.bool:
        r"""
        No storage/index rewrite was needed.
        """
    @property
    def tombstones_before(self) -> builtins.int:
        r"""
        Tombstones present before the pass.
        """
    @property
    def facts_before(self) -> builtins.int:
        r"""
        Fact records before the pass.
        """
    @property
    def facts_after(self) -> builtins.int:
        r"""
        Fact records after the pass.
        """
    @property
    def vectors_before(self) -> builtins.int:
        r"""
        Vector slots before the pass.
        """
    @property
    def vectors_after(self) -> builtins.int:
        r"""
        Vector slots after the pass.
        """
    @property
    def hnsw_indexed_before(self) -> builtins.int:
        r"""
        HNSW coverage before the pass.
        """
    @property
    def hnsw_indexed_after(self) -> builtins.int:
        r"""
        HNSW coverage after the pass.
        """
    @property
    def structural_compacted(self) -> builtins.bool:
        r"""
        Physical compaction ran.
        """
    @property
    def bm25_compacted(self) -> builtins.bool:
        r"""
        BM25 was compacted from existing postings.
        """
    @property
    def bm25_reindexed(self) -> builtins.bool:
        r"""
        BM25 was rebuilt from text.
        """
    @property
    def hnsw_rebuilt(self) -> builtins.bool:
        r"""
        HNSW was rebuilt from empty.
        """
    @property
    def hnsw_remapped(self) -> builtins.bool:
        r"""
        HNSW was carried/remapped.
        """
    @property
    def hnsw_inserted(self) -> builtins.int:
        r"""
        Vector slots inserted into HNSW.
        """
    @property
    def edges_compacted(self) -> builtins.bool:
        r"""
        The edge arenas were rewritten page-dense (`full` only). No edge version
        is ever dropped, so the version count is unchanged — only the bytes
        shrink.
        """
    @property
    def edges_before(self) -> builtins.int:
        r"""
        Current edges before the pass.
        """
    @property
    def edge_versions_before(self) -> builtins.int:
        r"""
        Historical edge versions before the pass.
        """
    def __repr__(self) -> builtins.str: ...

class NeedsCheckpointError(PlugmemError):
    r"""
    A read-only open needs a published snapshot and the writer has not checkpointed yet.
    """
    ...

class OpenError(PlugmemError):
    r"""
    Opening failed for any other reason — IO, or an image that will not load.
    """
    ...

@typing.final
class Plugmem:
    r"""
    A memory over one plugmem database — the Python mirror of
    `plugmem_host::Database` (writer) or `ReadOnlyDatabase` (`read_only=True`).
    
    Open it with [`Plugmem::open`], call the verbs, and `close()` it to release
    the file. It is also a context manager, so `with Plugmem.open(path) as db:`
    closes it for you.
    """
    @staticmethod
    def open(path: typing.Optional[builtins.str] = None, *, dim: typing.Optional[builtins.int] = None, read_only: builtins.bool = ..., config: typing.Optional[builtins.str] = None) -> Plugmem:
        r"""
        Open (or create) the memory at `path` and return the handle.
        
        With `path` omitted, resolution is `PLUGMEM_DB`, then `[database].path`
        from the config, then the platform data path — and [`path`](Self::path)
        reports which it was.
        
        `dim` is the embedding dimension; omit it or pass 0 to keep vectors off.
        `read_only=True` opens over another process's writer and needs a
        published snapshot. `config` points at a `config.toml`; omitted, the
        standard discovery applies (`$PLUGMEM_CONFIG`, then the platform config
        path), exactly as the CLI and MCP server resolve it.
        
        Raises `LockedError` if another writer holds the lock,
        `NeedsCheckpointError` if `read_only` is asked of a database nobody has
        checkpointed, `ConfigError` for a bad `config.toml`, and `OpenError`
        otherwise.
        """
    def config_warnings(self) -> builtins.list[builtins.str]:
        r"""
        What `config.toml` said that nothing claimed — a misspelled key, a
        misspelled section — one human-readable line each, empty when the file
        was clean.
        
        It is a value rather than a printed warning because a library has
        nowhere sensible to print: stderr belongs to the application, which may
        be a server that logs as JSON. **Read it once after opening and log it
        your own way** — ignoring it puts you back where a typo silently
        changes nothing.
        """
    def path(self) -> builtins.str:
        r"""
        The database this memory is open on.
        
        Worth having because `open` may resolve the path rather than be given
        one, and a caller that passed nothing otherwise cannot say what it just
        wrote to.
        """
    def remember(self, text: builtins.str, *, entity: typing.Optional[builtins.str] = None, tags: typing.Optional[typing.Sequence[builtins.str]] = None, links: typing.Optional[typing.Sequence[tuple[builtins.str, builtins.str]]] = None, metadata: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, valid_from: typing.Optional[builtins.int] = None, vector: typing.Optional[typing.Sequence[builtins.float]] = None) -> RememberOutcome:
        r"""
        Store one fact and return its id plus similar/conflicting live facts.
        
        The engine never merges on its own: `similar` is the hint, and what to
        do about it — revise, forget, keep both — is the caller's decision.
        """
    def remember_guarded(self, text: builtins.str, *, entity: typing.Optional[builtins.str] = None, tags: typing.Optional[typing.Sequence[builtins.str]] = None, links: typing.Optional[typing.Sequence[tuple[builtins.str, builtins.str]]] = None, metadata: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, valid_from: typing.Optional[builtins.int] = None, vector: typing.Optional[typing.Sequence[builtins.float]] = None) -> GuardedRememberOutcome:
        r"""
        Store only when the same bounded Jaccard/cosine detector used by
        `remember().similar` finds no candidate. The GIL is released while the
        automatic embedder and race-free check/conditional-write operation run.
        """
    def remember_many(self, facts: collections.abc.Sequence[collections.abc.Mapping[builtins.str, typing.Any]]) -> builtins.list[RememberOutcome]:
        r"""
        Store a batch of facts and return one outcome per input.
        
        Each item is a mapping with `remember`'s keyword names (`text` is
        required). One journal write and one embedding round trip for the whole
        batch, which is the point.
        """
    def revise(self, id: builtins.int, text: builtins.str, *, entity: typing.Optional[builtins.str] = None, tags: typing.Optional[typing.Sequence[builtins.str]] = None, links: typing.Optional[typing.Sequence[tuple[builtins.str, builtins.str]]] = None, metadata: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, valid_from: typing.Optional[builtins.int] = None, vector: typing.Optional[typing.Sequence[builtins.float]] = None) -> RememberOutcome:
        r"""
        Supersede a fact: close the old one's validity interval and record the
        successor, keeping the chain so an as-of query still answers about the
        old one.
        """
    def recall(self, query: typing.Optional[builtins.str] = None, *, tags: typing.Optional[typing.Sequence[builtins.str]] = None, entities: typing.Optional[typing.Sequence[builtins.str]] = None, as_of: typing.Optional[builtins.int] = None, range: typing.Optional[tuple[builtins.int, builtins.int]] = None, k: builtins.int = ..., closed: builtins.bool = ..., token_budget: typing.Optional[builtins.int] = None, ef: typing.Optional[builtins.int] = None, graph_depth: typing.Optional[builtins.int] = None, vector: typing.Optional[typing.Sequence[builtins.float]] = None) -> RecallResult:
        r"""
        Answer a query with ranked facts, the edges the graph source walked, and
        a rendered block bounded by `token_budget`.
        
        `as_of` is the truth axis ("what was true then"); `range` is a
        `(from, to)` window over the knowledge axis. `graph_depth` overrides the
        configured default for this call alone, because how wide a net to cast
        belongs to the question.
        """
    def forget(self, id: builtins.int) -> builtins.bool:
        r"""
        Tombstone a fact. Returns `True` if it was there to forget.
        
        The record is removed physically by `maintain`, not here — forgetting is
        a decision, purging is bookkeeping.
        """
    def forget_many(self, ids: typing.Sequence[builtins.int]) -> builtins.list[builtins.bool]:
        r"""
        Tombstone a batch of facts. Returns one `True`/`False` per id, in order.
        
        Equivalent to `forget` on each id in order, but under one journal write
        and one post-write policy pass — the batching `remember_many` does for
        writes, mirrored here since there is no embedder in the way.
        """
    def link(self, src: builtins.str, rel: builtins.str, dst: builtins.str, *, provenance: typing.Optional[builtins.int] = None) -> None:
        r"""
        Open a typed edge `src -[rel]-> dst`.
        
        `provenance` records the fact the edge follows from, which is what makes
        "why is this edge here" answerable later.
        """
    def unlink(self, src: builtins.str, rel: builtins.str, dst: builtins.str) -> builtins.bool:
        r"""
        Close an edge as of now. Returns `True` if an open one was there.
        
        The edge's history survives: an as-of query before this instant still
        walks it. That is why there is no "delete edge".
        """
    def get(self, id: builtins.int) -> typing.Optional[FactSnapshot]:
        r"""
        One fact's full card, or `None` if no such live fact exists.
        """
    def tags_of(self, id: builtins.int) -> builtins.list[builtins.str]:
        r"""
        A fact's tags, as strings.
        """
    def list_tags(self, *, prefix: typing.Optional[builtins.str] = None, cursor: typing.Optional[builtins.str] = None, limit: builtins.int = ...) -> TagPage:
        r"""
        One bounded page of current tags in lexical order.
        """
    def remove_tag(self, tag: builtins.str) -> RemoveTagReport:
        r"""
        Remove a tag from all current facts, preserving historical revisions.
        """
    def stats(self) -> Stats:
        r"""
        Engine size counters.
        """
    def export(self) -> builtins.list[ExportedFact]:
        r"""
        Every open fact, in one list.
        
        Fine for a memory you can hold in memory; for anything larger use
        [`export_page`](Self::export_page), which is the same dump in bounded
        pieces.
        """
    def export_page(self, cursor: typing.Optional[builtins.int] = None) -> ExportPage:
        r"""
        One bounded page of open facts, in fact-id order.
        
        Pass `None` to start and then the page's `next_cursor` until it is
        `None`. `export_pages()` wraps this as a generator.
        """
    def export_edges(self, on_batch: collections.abc.Callable[[builtins.list[ExportedEdge]], typing.Any]) -> builtins.int:
        r"""
        Stream every edge to `on_batch`, a list of `ExportedEdge` at a time.
        Returns the total number of edges handed over.
        
        Batched rather than one call per edge because each call has to reattach
        to the interpreter: the walk itself runs with the GIL released, and the
        GIL is taken only to hand over a finished list.
        
        A dump is the two streams together — `export`/`export_page` for facts
        and this for edges. An edge is a statement *between* entities and
        outlives any single fact, so it is not part of a fact's record.
        """
    def verify(self) -> None:
        r"""
        Check every index against the facts. Raises `EngineError` on the first
        inconsistency, returns `None` when the engine is coherent.
        
        This is the *logical* check. The byte-level one is [`scrub`](Self::scrub).
        """
    def scrub(self, budget: typing.Optional[builtins.int] = None) -> Scrub:
        r"""
        A resumable byte-level check of the published snapshot.
        
        `verify` asks whether the indexes agree with the facts; this asks
        whether the bytes on disk are the bytes that were written. It holds a
        shared lock on the generation for as long as the returned object lives,
        so the writer's collector cannot recycle the file underneath it — drop
        the object, or call `close()`, to let go.
        """
    def maintain(self, mode: builtins.str = ...) -> MaintainReport:
        r"""
        Run a maintenance pass and return what it did.
        
        `mode` is one of `"auto"` (the default: only pending work, cheap to run
        often), `"compact"`, `"reindex-text"`, `"optimize-vectors"` or `"full"`.
        """
    def reembed(self, batch_size: builtins.int = ...) -> ReembedReport:
        r"""
        Explicitly replace the complete vector axis with the configured
        embedder. This is separate from `maintain`; `auto` never invokes it.
        The GIL is released for the provider and snapshot work. In async code,
        use `await asyncio.to_thread(db.reembed)` like every other synchronous
        database verb that may take noticeable wall time.
        """
    def checkpoint(self) -> None:
        r"""
        Publish a snapshot and truncate the journal.
        
        Also what makes the memory readable: a reader needs a published
        generation, so a database nobody has checkpointed cannot be opened
        `read_only=True`.
        """
    def generation(self) -> builtins.int:
        r"""
        Which published generation this reader is looking at.
        
        Read-only handles only: a writer always sees its own latest state, so
        asking it raises `WriterOnlyError` rather than returning a number that
        would mean something different.
        """
    def refresh(self) -> builtins.bool:
        r"""
        Point this reader at the newest published generation. Returns `True` if
        it moved.
        
        Takes the handle exclusively, so it waits for in-flight reads on this
        object rather than swapping the mapping underneath them.
        """
    def close(self) -> None:
        r"""
        Release the database: unmap, drop the lock, and make every later verb
        raise `ClosedError`. Calling it twice is fine.
        """
    def __enter__(self) -> Plugmem:
        r"""
        `with Plugmem.open(path) as db:` — returns the handle itself.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any] = None, _exc_value: typing.Optional[typing.Any] = None, _traceback: typing.Optional[typing.Any] = None) -> builtins.bool:
        r"""
        Closes the memory when the `with` block ends, however it ends.
        """
    def __repr__(self) -> builtins.str: ...

class PlugmemError(builtins.Exception):
    code: typing.ClassVar[builtins.str]
    r"""
    Base class for every failure plugmem decides. Carries a stable `code`.
    """
    ...

class ReadOnlyError(PlugmemError):
    r"""
    A write verb was called on a read-only handle.
    """
    ...

@typing.final
class RecallResult:
    r"""
    A recall response: the structured hits plus the bounded rendered block.
    """
    @property
    def facts(self) -> builtins.list[RecalledFact]:
        r"""
        Selected facts, descending fused score.
        """
    @property
    def edges(self) -> builtins.list[RecalledEdge]:
        r"""
        Edges the graph source walked (deduplicated).
        """
    @property
    def rendered(self) -> builtins.str:
        r"""
        The compact rendered block (empty when nothing was found).
        """
    @property
    def truncated(self) -> builtins.bool:
        r"""
        `true` when selection stopped at `k`/the token budget with more left.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RecalledEdge:
    r"""
    One edge walked by the graph source.
    """
    @property
    def src(self) -> builtins.int:
        r"""
        Source entity id.
        """
    @property
    def rel(self) -> builtins.int:
        r"""
        Relation term id.
        """
    @property
    def dst(self) -> builtins.int:
        r"""
        Destination entity id.
        """
    @property
    def provenance(self) -> builtins.int:
        r"""
        Provenance fact id (a sentinel when none).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RecalledFact:
    r"""
    One recalled fact.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        The fact id.
        """
    @property
    def score(self) -> builtins.float:
        r"""
        Fused score (reciprocal-rank fusion + recency).
        """
    @property
    def sources(self) -> builtins.int:
        r"""
        Bit set of the sources that surfaced it.
        """
    @property
    def entity(self) -> builtins.int:
        r"""
        Subject entity id (a sentinel when none).
        """
    @property
    def recorded_at(self) -> builtins.int:
        r"""
        Knowledge axis: when the memory learned it (unix ms).
        """
    @property
    def valid_from(self) -> builtins.int:
        r"""
        Truth axis start (unix ms).
        """
    @property
    def valid_to(self) -> builtins.int:
        r"""
        Truth axis end (unix ms), or `VALID_TO_OPEN` while the fact is open.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RecoverReport:
    r"""
    What a `recover` salvaged, and what it had to leave behind.
    
    The three `dropped` counts are the damage: each is a fact the source could
    not produce intact, so a non-zero total means the recovered copy is smaller
    than the original claimed to be. Zeroes across the board mean the image was
    content-clean and this was a compaction.
    """
    @property
    def kept(self) -> builtins.int:
        r"""
        Facts written to the destination — the survivors.
        """
    @property
    def dropped_text(self) -> builtins.int:
        r"""
        Dropped: the stored text was not valid UTF-8.
        """
    @property
    def dropped_vector(self) -> builtins.int:
        r"""
        Dropped: the vector slot was out of range or disagreed with the fact.
        """
    @property
    def dropped_metadata(self) -> builtins.int:
        r"""
        Dropped: the metadata blob did not decode to a well-formed map.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ReembedReport:
    r"""
    The report of an explicit complete vector-axis replacement.
    """
    @property
    def previous_space(self) -> typing.Optional[builtins.str]: ...
    @property
    def new_space(self) -> builtins.str: ...
    @property
    def previous_dim(self) -> builtins.int: ...
    @property
    def new_dim(self) -> builtins.int: ...
    @property
    def embedded(self) -> builtins.int: ...
    @property
    def tombstones_skipped(self) -> builtins.int: ...
    @property
    def vector_bytes(self) -> builtins.int: ...
    @property
    def hnsw_indexed(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ReindexReport:
    r"""
    What a `Workspace.reindex()` pass did.
    """
    @property
    def indexed(self) -> builtins.list[builtins.str]:
        r"""
        Memories whose own description was copied into the registry.
        """
    @property
    def undescribed(self) -> builtins.list[builtins.str]:
        r"""
        Memories nobody has described. Not a fault — a memory works without a
        description; it just cannot be found by one.
        """
    @property
    def busy(self) -> builtins.list[builtins.str]:
        r"""
        Memories another process holds open, so this pass could not read them.
        Named rather than skipped silently: the registry is knowingly incomplete.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RememberOutcome:
    r"""
    The result of `remember` / `revise`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        The new fact's id.
        """
    @property
    def entity(self) -> typing.Optional[builtins.int]:
        r"""
        The subject entity id, if one was named.
        """
    @property
    def similar(self) -> builtins.list[Similar]:
        r"""
        Similar / potentially-conflicting live facts (best first; the engine
        never merges on its own — the caller decides).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RemoveTagReport:
    r"""
    Result of removing one tag from all current facts.
    """
    @property
    def affected(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Scrub:
    r"""
    A resumable byte-level check of one snapshot generation.
    
    **Holding this object holds a lock.** It pins the generation it is scanning
    with a shared lock for its whole life, so the writer's garbage collection
    cannot reclaim that generation under it. Finish the scan, or `close()` it —
    do not park one indefinitely. It is also a context manager, so
    `with db.scrub() as scan:` releases the pin however the block ends.
    
    One-shot: once it has returned `None`, or raised, it is done. Ask the
    database for another to scan again.
    """
    def next(self) -> typing.Optional[ScrubProgress]:
        r"""
        Hash the next budget's worth of bytes and report progress, or return
        `None` when the generation has been checked end to end.
        
        Raises `EngineError` on a mismatch, naming the section — that is the
        scrub finding what it was looking for.
        """
    def close(self) -> None:
        r"""
        Release the pinned generation now. Calling it twice is fine.
        """
    def active(self) -> builtins.bool:
        r"""
        Whether the scan is still holding its generation and has steps left.
        """
    def __iter__(self) -> Scrub:
        r"""
        `for progress in db.scrub():` — the iterator is the scrub itself.
        """
    def __next__(self) -> ScrubProgress:
        r"""
        One step, in the iterator protocol's terms. The same step `next()`
        takes; exhaustion is `StopIteration` instead of `None`.
        """
    def __enter__(self) -> Scrub:
        r"""
        `with db.scrub() as scan:` — returns the scrub itself.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any] = None, _exc_value: typing.Optional[typing.Any] = None, _traceback: typing.Optional[typing.Any] = None) -> builtins.bool:
        r"""
        Releases the pinned generation when the `with` block ends.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ScrubProgress:
    r"""
    How far a `Scrub` has got.
    """
    @property
    def done_bytes(self) -> builtins.int:
        r"""
        Bytes checksummed so far; equals `total_bytes` on the last step.
        """
    @property
    def total_bytes(self) -> builtins.int:
        r"""
        The generation file's length — the total to checksum.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SettingHelpItem:
    r"""
    One `config.toml` setting returned by `settings_help`.
    
    `Clone` because it is read through a getter on [`SettingsHelpResult`], and a
    getter hands out a copy rather than a borrow into a frozen object.
    `skip_from_py_object` because it only ever travels outward: nothing in this
    binding accepts one as an argument.
    """
    @property
    def section(self) -> builtins.str:
        r"""
        TOML section name.
        """
    @property
    def key(self) -> builtins.str:
        r"""
        TOML key name.
        """
    @property
    def value_type(self) -> builtins.str:
        r"""
        Human-readable value type.
        """
    @property
    def default_value(self) -> builtins.str:
        r"""
        Displayed default value.
        """
    @property
    def description(self) -> builtins.str:
        r"""
        What the setting does.
        """
    @property
    def scope(self) -> builtins.str:
        r"""
        Owning surface: shared, CLI or MCP.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SettingsHelpResult:
    r"""
    Complete `config.toml` help returned by `settings_help`.
    """
    @property
    def config_path_precedence(self) -> builtins.list[builtins.str]:
        r"""
        Config discovery order from highest to lowest precedence.
        """
    @property
    def default_config_path(self) -> typing.Optional[builtins.str]:
        r"""
        Resolved platform default config path, if the OS exposes a user home.
        """
    @property
    def settings(self) -> builtins.list[SettingHelpItem]:
        r"""
        Every supported `config.toml` setting.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Similar:
    r"""
    One similar / potentially-conflicting live fact surfaced by `remember`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        The existing fact's id.
        """
    @property
    def score(self) -> builtins.float:
        r"""
        Match strength (higher = closer).
        """
    @property
    def reason(self) -> builtins.str:
        r"""
        What triggered the hint: `"LexicalOverlap"` or `"VectorCosine"`.
        """
    def __repr__(self) -> builtins.str: ...

class StaleCursorError(PlugmemError):
    r"""
    A tag page cursor no longer names the current catalogue snapshot.
    """
    ...

@typing.final
class Stats:
    r"""
    Engine size counters.
    """
    @property
    def facts(self) -> builtins.int:
        r"""
        Fact records stored (live, closed and tombstoned-awaiting-maintain).
        """
    @property
    def entities(self) -> builtins.int:
        r"""
        Entities.
        """
    @property
    def terms(self) -> builtins.int:
        r"""
        Interned terms (tokens, tags, relations, names).
        """
    @property
    def edges(self) -> builtins.int:
        r"""
        Directed edges.
        """
    @property
    def edge_versions(self) -> builtins.int:
        r"""
        Historical edge versions, including closed versions.
        """
    @property
    def vectors(self) -> builtins.int:
        r"""
        Quantized vector slots.
        """
    @property
    def tombstones(self) -> builtins.int:
        r"""
        Tombstoned fact records awaiting physical purge.
        """
    @property
    def hnsw_indexed(self) -> builtins.int:
        r"""
        Vector slots covered by HNSW.
        """
    @property
    def next_fact(self) -> builtins.int:
        r"""
        The next fact id to be assigned.
        """
    @property
    def next_entity(self) -> builtins.int:
        r"""
        The next entity id to be assigned.
        """
    @property
    def next_edge(self) -> builtins.int:
        r"""
        The next edge-version id to be assigned.
        """
    @property
    def pool_bytes(self) -> builtins.int:
        r"""
        Total bytes held by the engine's pools.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TagPage:
    r"""
    One bounded page of current tags.
    """
    @property
    def items(self) -> builtins.list[TagSummary]: ...
    @property
    def next_cursor(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TagSummary:
    r"""
    One active tag and the number of current facts carrying it.
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def count(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Workspace:
    r"""
    A directory of named memories — the Python mirror of
    `plugmem_host::Workspace`.
    
    The lock guards the handle slot, not the workspace: `plugmem_host::Workspace`
    synchronizes its own pool and registry, so what needs protecting here is only
    the `Option` that `close()` empties while other threads may be inside a verb.
    """
    def __new__(cls, root: builtins.str, *, dim: typing.Optional[builtins.int] = None, config: typing.Optional[builtins.str] = None, max_open: typing.Optional[builtins.int] = None, idle_timeout_ms: typing.Optional[builtins.int] = None) -> Workspace:
        r"""
        Open the workspace rooted at `root`. Creates nothing: the directories
        appear when a memory is first written.
        
        `dim` applies to every memory in the workspace and to the registry.
        `config` points at a `config.toml` whose `[workspace]` section supplies
        the pool defaults; `max_open` and `idle_timeout_ms` override them.
        
        `idle_timeout_ms` is a liveness setting, not a memory one: an open
        memory holds that database's exclusive lock, so a long-running process
        that never let go would make its memories unreachable from anything else
        on the machine.
        """
    def memory(self, db: builtins.str) -> WorkspaceMemory:
        r"""
        Return a logical reference to the memory named `db`.
        
        This does not open a file, acquire a lock or create the memory. Read
        verbs require it to exist; write verbs create it on first use. The
        reference stays valid across pool eviction and `release()`.
        """
    def release(self, db: builtins.str) -> builtins.bool:
        r"""
        Evict one inactive memory and release its file lock. Logical references
        remain valid. If a verb is using this memory, raises
        `BusyError` immediately instead of waiting.
        """
    def list(self) -> builtins.list[builtins.str]:
        r"""
        Every memory name in the directory, whether or not the registry knows
        about it. This is the filesystem's answer, so a memory created by
        another process appears here immediately.
        """
    def entries(self) -> builtins.list[DbEntry]:
        r"""
        Every memory the registry has a record for, with its description, tags,
        owner and archived flag.
        """
    def find(self, query: builtins.str, *, k: builtins.int = ...) -> builtins.list[DbEntry]:
        r"""
        Search the descriptions and return the best matches — the answer to
        "which memory is the one about X" when the caller does not know the name.
        """
    def describe(self, db: builtins.str, description: builtins.str, *, tags: typing.Optional[typing.Sequence[builtins.str]] = None, owner: typing.Optional[builtins.str] = None) -> None:
        r"""
        Record what a memory is for. `description` is the text `find` matches;
        `owner` is recorded as a graph edge, so `find("ann")` returns what Ann
        owns even though no description mentions her.
        """
    def archive(self, db: builtins.str) -> builtins.bool:
        r"""
        Label a memory archived. Returns `True` if the label changed.
        
        Nothing is deleted and the memory still opens: this is a filter for
        `find`, not a lifecycle.
        """
    def reindex(self) -> ReindexReport:
        r"""
        Copy each memory's own description into the registry, and report which
        were indexed, which nobody has described, and which another process held
        open so this pass could not read them.
        """
    def verify(self) -> builtins.list[WorkspaceProblem]:
        r"""
        Report what disagrees between the directory and the registry. Findings
        only: nothing is repaired, because which side is right is a judgement.
        """
    def close_idle(self) -> builtins.int:
        r"""
        Close memories idle longer than the configured timeout and return how
        many were closed. Each close releases that database's exclusive lock.
        """
    def open_count(self) -> builtins.int:
        r"""
        How many memories the pool currently holds open.
        """
    def close(self) -> None:
        r"""
        Invalidate every logical memory reference and close pooled memories.
        Calling it twice is fine. An already-running verb releases its scoped
        handle when that call returns.
        """
    def __enter__(self) -> Workspace:
        r"""
        `with Workspace(root) as ws:` — returns the workspace itself.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any] = None, _exc_value: typing.Optional[typing.Any] = None, _traceback: typing.Optional[typing.Any] = None) -> builtins.bool:
        r"""
        Closes the workspace when the `with` block ends, however it ends.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class WorkspaceMemory:
    r"""
    A logical reference to one named memory. It owns no open database and no
    file lock. Each verb obtains one scoped
    lease while the GIL is released. Dropping this Python object has no resource
    meaning; closing the workspace invalidates every reference.
    """
    def name(self) -> builtins.str:
        r"""
        The stable workspace name this reference addresses.
        """
    def remember(self, text: builtins.str, *, entity: typing.Optional[builtins.str] = None, tags: typing.Optional[typing.Sequence[builtins.str]] = None, links: typing.Optional[typing.Sequence[tuple[builtins.str, builtins.str]]] = None, metadata: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, valid_from: typing.Optional[builtins.int] = None, vector: typing.Optional[typing.Sequence[builtins.float]] = None) -> RememberOutcome: ...
    def remember_guarded(self, text: builtins.str, *, entity: typing.Optional[builtins.str] = None, tags: typing.Optional[typing.Sequence[builtins.str]] = None, links: typing.Optional[typing.Sequence[tuple[builtins.str, builtins.str]]] = None, metadata: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, valid_from: typing.Optional[builtins.int] = None, vector: typing.Optional[typing.Sequence[builtins.float]] = None) -> GuardedRememberOutcome: ...
    def remember_many(self, facts: collections.abc.Sequence[collections.abc.Mapping[builtins.str, typing.Any]]) -> builtins.list[RememberOutcome]: ...
    def revise(self, id: builtins.int, text: builtins.str, *, entity: typing.Optional[builtins.str] = None, tags: typing.Optional[typing.Sequence[builtins.str]] = None, links: typing.Optional[typing.Sequence[tuple[builtins.str, builtins.str]]] = None, metadata: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, valid_from: typing.Optional[builtins.int] = None, vector: typing.Optional[typing.Sequence[builtins.float]] = None) -> RememberOutcome: ...
    def recall(self, query: typing.Optional[builtins.str] = None, *, tags: typing.Optional[typing.Sequence[builtins.str]] = None, entities: typing.Optional[typing.Sequence[builtins.str]] = None, as_of: typing.Optional[builtins.int] = None, range: typing.Optional[tuple[builtins.int, builtins.int]] = None, k: builtins.int = ..., closed: builtins.bool = ..., token_budget: typing.Optional[builtins.int] = None, ef: typing.Optional[builtins.int] = None, graph_depth: typing.Optional[builtins.int] = None, vector: typing.Optional[typing.Sequence[builtins.float]] = None) -> RecallResult: ...
    def forget(self, id: builtins.int) -> builtins.bool: ...
    def forget_many(self, ids: typing.Sequence[builtins.int]) -> builtins.list[builtins.bool]: ...
    def link(self, src: builtins.str, rel: builtins.str, dst: builtins.str, *, provenance: typing.Optional[builtins.int] = None) -> None: ...
    def unlink(self, src: builtins.str, rel: builtins.str, dst: builtins.str) -> builtins.bool: ...
    def get(self, id: builtins.int) -> typing.Optional[FactSnapshot]: ...
    def tags_of(self, id: builtins.int) -> builtins.list[builtins.str]: ...
    def list_tags(self, *, prefix: typing.Optional[builtins.str] = None, cursor: typing.Optional[builtins.str] = None, limit: builtins.int = ...) -> TagPage: ...
    def remove_tag(self, tag: builtins.str) -> RemoveTagReport: ...
    def stats(self) -> Stats: ...
    def export(self) -> builtins.list[ExportedFact]: ...
    def export_page(self, cursor: typing.Optional[builtins.int] = None) -> ExportPage: ...
    def export_edges(self, on_batch: collections.abc.Callable[[builtins.list[ExportedEdge]], typing.Any]) -> builtins.int: ...
    def verify(self) -> None: ...
    def scrub(self, budget: typing.Optional[builtins.int] = None) -> Scrub: ...
    def maintain(self, mode: builtins.str = ...) -> MaintainReport: ...
    def reembed(self, batch_size: builtins.int = ...) -> ReembedReport: ...
    def checkpoint(self) -> None: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class WorkspaceProblem:
    r"""
    Something `Workspace.verify()` found. Reported, never repaired.
    """
    @property
    def db(self) -> builtins.str:
        r"""
        The memory it concerns (empty for a kind this binding does not know).
        """
    @property
    def issue(self) -> builtins.str:
        r"""
        What kind: `"missing"`, `"undescribed"`, `"stale"`, `"unreadable"`,
        `"ambiguous-self"`. The same vocabulary the CLI prints in `--json`.
        """
    @property
    def detail(self) -> typing.Optional[builtins.str]:
        r"""
        More detail, where the kind carries any.
        """
    def __repr__(self) -> builtins.str: ...

class WriterOnlyError(PlugmemError):
    r"""
    A read-only-only verb (`generation`, `refresh`) was called on a writer.
    """
    ...

def about() -> builtins.str:
    r"""
    A short, version-free description pointing the caller at the skill.
    """

def recover(src: builtins.str, dst: builtins.str, *, dim: typing.Optional[builtins.int] = None, config: typing.Optional[builtins.str] = None) -> RecoverReport:
    r"""
    Salvage a content-corrupt memory into a clean copy.
    
    Reads `src` fact by fact, writes what survives to `dst`, and reports what it
    had to drop. The source is left untouched as evidence, and `dst` must not be
    `src`.
    
    This is not a repair for *structural* damage: a snapshot that will not parse
    cannot be walked, and that case is a restore from backup, not a recovery.
    """

def settings_help() -> SettingsHelpResult:
    r"""
    Return the complete `config.toml` settings catalogue without opening a
    database.
    """

def skill() -> builtins.str:
    r"""
    The companion skill for Python consumers: the canonical `SKILL.md` with the
    CLI/MCP "Run it" appendix removed (an embedding application has one
    transport and always ships skill and engine from the same release, so that
    ceremony never applies).
    """

def skill_full() -> builtins.str:
    r"""
    The canonical, unstripped `SKILL.md` (what CLI/MCP consumers read).
    """

def skill_version() -> builtins.str:
    r"""
    The `<!-- skill-version: X.Y.Z -->` marker value from the canonical skill
    (read from the raw text, so the marker living inside the stripped block is
    still visible here).
    """

def version() -> builtins.str:
    r"""
    The engine/package version (the workspace version; the PyPI package tracks
    it release-for-release).
    """

