"""The gate that keeps this binding equal to the Node one.

`plugmem-napi`'s `index.d.ts` is generated by its build and already gated in
CI, which makes it the honest record of what the Node surface is. This test
reads it, converts camelCase to snake_case, and requires the two surfaces to
name exactly the same things.

It fails in *both* directions on purpose. A name only Node has is a gap here; a
name only Python has is a third surface being born. The wrapper-parity rule in
`AGENTS.md` treats either as a bug, and without a test the rule is a document
nobody rereads — which is exactly how the plan for this crate went stale before
a line of it was written.
"""

from __future__ import annotations

import re
from pathlib import Path

import plugmem
import pytest

NAPI_DTS = Path(__file__).resolve().parents[2] / "plugmem-napi" / "index.d.ts"

# Idioms Python demands and JavaScript cannot express. Each is sugar over a verb
# that IS in the shared surface, never a capability of its own — see the module
# docstrings of `db.rs`, `scrub.rs` and `__init__.py`.
PYTHON_ONLY = {
    "__enter__",
    "__exit__",
    "__iter__",
    "__next__",
    "export_pages",
}


def camel_to_snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def napi_source() -> str:
    if not NAPI_DTS.is_file():
        pytest.skip(f"the Node binding's index.d.ts is not present at {NAPI_DTS}")
    return NAPI_DTS.read_text(encoding="utf-8")


def napi_class_members(source: str, class_name: str) -> set[str]:
    """Method names declared on one `export declare class` block."""
    start = source.index(f"export declare class {class_name} {{")
    depth = 0
    end = start
    for index in range(start, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                end = index
                break
    body = source[start:end]
    # `name(` or `static name(` at the start of a line, skipping doc comments.
    return {
        camel_to_snake(match.group(1))
        for match in re.finditer(
            r"^\s*(?:static\s+)?([a-zA-Z_]\w*)\s*\(", body, re.MULTILINE
        )
        if match.group(1) not in {"constructor", "if", "for", "while"}
    }


def napi_functions(source: str) -> set[str]:
    return {
        camel_to_snake(match.group(1))
        for match in re.finditer(
            r"^export declare function (\w+)", source, re.MULTILINE
        )
    }


def python_members(cls: type) -> set[str]:
    return {
        name
        for name in dir(cls)
        if (not name.startswith("_") or name in PYTHON_ONLY)
        and callable(getattr(cls, name, None))
    }


@pytest.mark.parametrize(
    "class_name", ["Plugmem", "Scrub", "Workspace", "WorkspaceMemory"]
)
def test_every_class_names_exactly_what_node_names(class_name: str) -> None:
    source = napi_source()
    node = napi_class_members(source, class_name)
    python = python_members(getattr(plugmem, class_name)) - PYTHON_ONLY

    # napi spells the workspace constructor `constructor`; Python spells it
    # `Workspace(...)`. Same thing, different keyword.
    node.discard("constructor")

    assert node - python == set(), (
        f"{class_name}: the Node binding has verbs this one does not"
    )
    assert python - node == set(), (
        f"{class_name}: this binding has verbs the Node one does not — either "
        f"add them there or make them Python idioms in PYTHON_ONLY"
    )


def test_module_functions_match() -> None:
    node = napi_functions(napi_source())
    python = {
        name
        for name in plugmem.__all__
        if callable(getattr(plugmem, name))
        and not isinstance(getattr(plugmem, name), type)
    } - PYTHON_ONLY
    assert node == python


def test_every_error_code_matches_the_node_binding() -> None:
    # The codes are the cross-language contract: a program that learned
    # PLUGMEM_LOCKED from Node must read the same string here.
    expected = {
        plugmem.LockedError: "PLUGMEM_LOCKED",
        plugmem.NeedsCheckpointError: "PLUGMEM_NEEDS_CHECKPOINT",
        plugmem.ConfigError: "PLUGMEM_CONFIG",
        plugmem.OpenError: "PLUGMEM_OPEN",
        plugmem.InvalidArgError: "PLUGMEM_INVALID_ARG",
        plugmem.InvalidNameError: "PLUGMEM_INVALID_NAME",
        plugmem.ClosedError: "PLUGMEM_CLOSED",
        plugmem.ReadOnlyError: "PLUGMEM_READ_ONLY",
        plugmem.WriterOnlyError: "PLUGMEM_WRITER_ONLY",
        plugmem.BusyError: "PLUGMEM_BUSY",
        plugmem.EngineError: "PLUGMEM_ENGINE",
        plugmem.InternalError: "PLUGMEM_INTERNAL",
    }
    for cls, code in expected.items():
        assert cls.code == code
        assert issubclass(cls, plugmem.PlugmemError)

    # The codes are runtime values, so they live in the Node binding's
    # `error.rs` rather than in its generated declarations.
    napi_errors = NAPI_DTS.parent / "src" / "error.rs"
    if not napi_errors.is_file():
        pytest.skip(f"the Node binding's error.rs is not present at {napi_errors}")
    source = napi_errors.read_text(encoding="utf-8")
    for code in expected.values():
        assert f'"{code}"' in source, f"{code} is not a code the Node binding defines"


def test_the_skill_ships_and_carries_a_version() -> None:
    # Deliberately not `version() == skill_version()`. The skill's marker is
    # bumped with the feature that changes the skill; the crate version is
    # bumped afterwards, by its own release commit. Requiring them to agree
    # would make every feature branch red until the release, which is a rule
    # this repository does not have.
    assert len(plugmem.skill_version().split(".")) == 3
    assert "# plugmem" in plugmem.skill()
    assert plugmem.skill_full().count("wasm-strip") == 2
