// Type-level test: `index.d.ts` is generated by napi from the Rust surface, and
// nothing checked that the result was valid TypeScript — let alone that a
// consumer could actually use it under `strict`. This file is compiled by
// `npm run typecheck`; it is never executed.
//
// It is written the way a TypeScript host (Pi) would use the package: no `any`,
// no casts, and every inferred type asserted rather than assumed. A wrong
// inference fails the build here instead of at someone's call site.
import {
  Plugmem,
  Workspace,
  type DbEntry,
  type ExportedFact,
  type MaintainReport,
  type RecallResult,
  type ReindexReport,
  type RememberOutcome,
  type Stats,
  type WorkspaceProblem,
} from "../index.js";

/** Fails to compile unless `T` and `U` are exactly the same type. */
type Exact<T, U> = [T] extends [U] ? ([U] extends [T] ? true : false) : false;
function assertType<T extends true>(_: T): void {}

// ── one memory: the default ─────────────────────────────────────────────────

const db = new Plugmem("memory.plugmem", { dim: 0 });
const id: number = db.remember({ text: "prefers tokio", entity: "user" }).id;
const recalled: RecallResult = db.recall({ query: "tokio", k: 8 });
const rendered: string = recalled.rendered;
const stats: Stats = db.stats();
assertType<Exact<typeof stats.facts, number>>(true);

// The async verbs are promises, not callbacks.
const maintained: Promise<MaintainReport> = db.maintain("auto");
const checkpointed: Promise<void> = db.checkpoint();
const rememberedMany: Promise<RememberOutcome[]> = db.rememberMany([
  { text: "batch", tags: ["example"] },
]);
const tags: string[] = db.tagsOf(id);
const exportedEach: Promise<void> = db.exportEach((error, fact) => {
  if (error) throw error;
  const exported: ExportedFact = fact;
  void exported;
});

// A path is optional; options are optional; both may be omitted entirely.
const defaulted = new Plugmem();
defaulted.close();

// ── many memories: opt-in ───────────────────────────────────────────────────

const ws = new Workspace("/srv/memories", { maxOpen: 8, idleTimeoutMs: 60_000 });

// `open` hands back the same class, so a named memory has the same verbs. This
// is the assertion that would catch the binding drifting into a second type.
const chat: Plugmem = ws.open("chat-42");
assertType<Exact<ReturnType<Workspace["open"]>, Plugmem>>(true);

const names: string[] = ws.list();
const entries: DbEntry[] = ws.entries();
const hits: DbEntry[] = ws.find("release planning", 4);
assertType<Exact<DbEntry["archived"], boolean>>(true);
assertType<Exact<DbEntry["owner"], string | undefined>>(true);

ws.describe("chat-42", {
  description: "release planning",
  tags: ["kind:chat"],
  owner: "ann",
});
const archived: boolean = ws.archive("chat-42");
const rebuilt: Promise<ReindexReport> = ws.reindex();
const problems: Promise<WorkspaceProblem[]> = ws.verify();
const closed: number = ws.closeIdle();
const open: number = ws.openCount();

// `create` is optional and boolean; the second argument is not a path or an
// options bag, which is exactly the confusion a name-shaped API invites.
const strict: Plugmem = ws.open("chat-42", false);

// Everything above is referenced so `noUnusedLocals` keeps this file honest.
export const used = {
  id,
  rendered,
  maintained,
  checkpointed,
  rememberedMany,
  tags,
  exportedEach,
  chat,
  names,
  entries,
  hits,
  archived,
  rebuilt,
  problems,
  closed,
  open,
  strict,
};
