// Type-level test: `index.d.ts` is generated by napi from the Rust surface, and
// nothing checked that the result was valid TypeScript — let alone that a
// consumer could actually use it under `strict`. This file is compiled by
// `npm run typecheck`; it is never executed.
//
// It is written the way a TypeScript host (Pi) would use the package: no `any`,
// no casts, and every inferred type asserted rather than assumed. A wrong
// inference fails the build here instead of at someone's call site.
import {
  Plugmem,
  Workspace,
  type DbEntry,
  type ExportPage,
  type ExportedFact,
  type MaintainReport,
  type RecallResult,
  type ReindexReport,
  type RememberOutcome,
  type Stats,
  type WorkspaceProblem,
} from "../index.js";

/** Fails to compile unless `T` and `U` are exactly the same type. */
type Exact<T, U> = [T] extends [U] ? ([U] extends [T] ? true : false) : false;
function assertType<T extends true>(_: T): void {}

// ── one memory: the default ─────────────────────────────────────────────────

const db = new Plugmem("memory.plugmem", { dim: 0 });
// `remember`, `revise` and `recall` are promises: with an `[embedder]`
// configured each can make an HTTP call, and blocking the one thread that runs
// JavaScript for that would stall the whole process.
const remembered: Promise<RememberOutcome> = db.remember({
  text: "prefers tokio",
  entity: "user",
});
const revised: Promise<RememberOutcome> = db.revise(0, { text: "prefers smol" });
const recalledLater: Promise<RecallResult> = db.recall({ query: "tokio", k: 8 });
const recalled: RecallResult = await recalledLater;
const id: number = (await remembered).id;
const rendered: string = recalled.rendered;

// A precomputed embedding is accepted wherever the engine takes one, and
// replaces the embedder for that call.
const own: number[] = [0.1, -0.2];
const withOwnVector: Promise<RecallResult> = db.recall({ query: "tokio", vector: own });
const storedWithVector: Promise<RememberOutcome> = db.remember({ text: "x", vector: own });
const stats: Stats = db.stats();
assertType<Exact<typeof stats.facts, number>>(true);

// The async verbs are promises, not callbacks.
const maintained: Promise<MaintainReport> = db.maintain("auto");
const checkpointed: Promise<void> = db.checkpoint();
const rememberedMany: Promise<RememberOutcome[]> = db.rememberMany([
  { text: "batch", tags: ["example"] },
]);
const tags: string[] = db.tagsOf(id);
const exported: Promise<ExportedFact[]> = db.export();
const verified: Promise<void> = db.verify();
const forgotten: Promise<boolean> = db.forget(id);
const linked: Promise<void> = db.link({ src: "a", rel: "r", dst: "b" });
const unlinked: Promise<boolean> = db.unlink({ src: "a", rel: "r", dst: "b" });
const exportedPage: Promise<ExportPage> = db.exportPage();
const exportedPageAfter: Promise<ExportPage> = db.exportPage(128);
type PageFact = ExportPage["facts"][number];
assertType<Exact<PageFact, ExportedFact>>(true);

// A path is optional; options are optional; both may be omitted entirely.
// `path()` is how a caller learns which file that resolved to.
const defaulted = new Plugmem();
const resolvedPath: string = defaulted.path();
defaulted.close();

// A recall window is a pair of instants; the binding refuses any other shape at
// runtime, and the type says `number[]` because napi has no fixed-length arrays.
const windowed: Promise<RecallResult> = db.recall({ range: [0, Date.now()], asOf: Date.now() });

// ── many memories: opt-in ───────────────────────────────────────────────────

const ws = new Workspace("/srv/memories", { maxOpen: 8, idleTimeoutMs: 60_000 });

// `open` hands back the same class, so a named memory has the same verbs. This
// is the assertion that would catch the binding drifting into a second type.
const chat: Promise<Plugmem> = ws.open("chat-42");
assertType<Exact<ReturnType<Workspace["open"]>, Promise<Plugmem>>>(true);

const names: Promise<string[]> = ws.list();
const entries: Promise<DbEntry[]> = ws.entries();
const hits: Promise<DbEntry[]> = ws.find("release planning", 4);
assertType<Exact<DbEntry["archived"], boolean>>(true);
assertType<Exact<DbEntry["owner"], string | undefined>>(true);

const described: Promise<void> = ws.describe("chat-42", {
  description: "release planning",
  tags: ["kind:chat"],
  owner: "ann",
});
const archived: Promise<boolean> = ws.archive("chat-42");
const rebuilt: Promise<ReindexReport> = ws.reindex();
const problems: Promise<WorkspaceProblem[]> = ws.verify();
const closed: number = ws.closeIdle();
const open: number = ws.openCount();

// `create` is optional and boolean; the second argument is not a path or an
// options bag, which is exactly the confusion a name-shaped API invites.
const strict: Promise<Plugmem> = ws.open("chat-42", false);

// Everything above is referenced so `noUnusedLocals` keeps this file honest.
export const used = {
  id,
  rendered,
  maintained,
  checkpointed,
  rememberedMany,
  tags,
  exportedPage,
  exportedPageAfter,
  exported,
  verified,
  forgotten,
  linked,
  unlinked,
  revised,
  withOwnVector,
  storedWithVector,
  resolvedPath,
  windowed,
  chat,
  names,
  entries,
  hits,
  described,
  archived,
  rebuilt,
  problems,
  closed,
  open,
  strict,
};
